//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHORDS_VDWBuilder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAUSE_OF_DEATH
    {
        public string PERSON_ID { get; set; }
        public string COD { get; set; }
        public string DX_CODETYPE { get; set; }
        public string CAUSETYPE { get; set; }
        public string SOURCE { get; set; }
        public string CONFIDENCE { get; set; }
    }
}
