//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHORDS_VDWBuilder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENSUS_DEMOG
    {
        public int CENSUS_YEAR { get; set; }
        public string GEOCODE { get; set; }
        public string BLOCK { get; set; }
        public string CENSUS_DATA_SRC { get; set; }
        public string CHORDS_GEOLEVEL { get; set; }
        public string STATE { get; set; }
        public string COUNTY { get; set; }
        public string TRACT { get; set; }
        public string BLOCKGP { get; set; }
        public Nullable<int> HOUSES_N { get; set; }
        public Nullable<decimal> RA_NHS_WH { get; set; }
        public Nullable<decimal> RA_NHS_BL { get; set; }
        public Nullable<decimal> RA_NHS_AM { get; set; }
        public Nullable<decimal> RA_NHS_AS { get; set; }
        public Nullable<decimal> RA_NHS_HA { get; set; }
        public Nullable<decimal> RA_NHS_OT { get; set; }
        public Nullable<decimal> RA_NHS_ML { get; set; }
        public Nullable<decimal> RA_HIS_WH { get; set; }
        public Nullable<decimal> RA_HIS_BL { get; set; }
        public Nullable<decimal> RA_HIS_AM { get; set; }
        public Nullable<decimal> RA_HIS_AS { get; set; }
        public Nullable<decimal> RA_HIS_HA { get; set; }
        public Nullable<decimal> RA_HIS_OT { get; set; }
        public Nullable<decimal> RA_HIS_ML { get; set; }
        public Nullable<decimal> HOUSES_OCCUPIED { get; set; }
        public Nullable<decimal> HOUSES_OWN { get; set; }
        public Nullable<decimal> HOUSES_RENT { get; set; }
        public Nullable<decimal> HOUSES_UNOCC_FORRENT { get; set; }
        public Nullable<decimal> HOUSES_UNOCC_FORSALE { get; set; }
        public Nullable<decimal> HOUSES_UNOCC_RENTSOLD { get; set; }
        public Nullable<decimal> HOUSES_UNOCC_SEASONAL { get; set; }
        public Nullable<decimal> HOUSES_UNOCC_MIGRANT { get; set; }
        public Nullable<decimal> HOUSES_UNOCC_OTHER { get; set; }
        public Nullable<decimal> EDUCATION1 { get; set; }
        public Nullable<decimal> EDUCATION2 { get; set; }
        public Nullable<decimal> EDUCATION3 { get; set; }
        public Nullable<decimal> EDUCATION4 { get; set; }
        public Nullable<decimal> EDUCATION5 { get; set; }
        public Nullable<decimal> EDUCATION6 { get; set; }
        public Nullable<decimal> EDUCATION7 { get; set; }
        public Nullable<decimal> EDUCATION8 { get; set; }
        public Nullable<int> MEDFAMINCOME { get; set; }
        public Nullable<decimal> FAMINCOME1 { get; set; }
        public Nullable<decimal> FAMINCOME2 { get; set; }
        public Nullable<decimal> FAMINCOME3 { get; set; }
        public Nullable<decimal> FAMINCOME4 { get; set; }
        public Nullable<decimal> FAMINCOME5 { get; set; }
        public Nullable<decimal> FAMINCOME6 { get; set; }
        public Nullable<decimal> FAMINCOME7 { get; set; }
        public Nullable<decimal> FAMINCOME8 { get; set; }
        public Nullable<decimal> FAMINCOME9 { get; set; }
        public Nullable<decimal> FAMINCOME10 { get; set; }
        public Nullable<decimal> FAMINCOME11 { get; set; }
        public Nullable<decimal> FAMINCOME12 { get; set; }
        public Nullable<decimal> FAMINCOME13 { get; set; }
        public Nullable<decimal> FAMINCOME14 { get; set; }
        public Nullable<decimal> FAMINCOME15 { get; set; }
        public Nullable<decimal> FAMINCOME16 { get; set; }
        public Nullable<int> MEDHOUSINCOME { get; set; }
        public Nullable<decimal> HOUSINCOME1 { get; set; }
        public Nullable<decimal> HOUSINCOME2 { get; set; }
        public Nullable<decimal> HOUSINCOME3 { get; set; }
        public Nullable<decimal> HOUSINCOME4 { get; set; }
        public Nullable<decimal> HOUSINCOME5 { get; set; }
        public Nullable<decimal> HOUSINCOME6 { get; set; }
        public Nullable<decimal> HOUSINCOME7 { get; set; }
        public Nullable<decimal> HOUSINCOME8 { get; set; }
        public Nullable<decimal> HOUSINCOME9 { get; set; }
        public Nullable<decimal> HOUSINCOME10 { get; set; }
        public Nullable<decimal> HOUSINCOME11 { get; set; }
        public Nullable<decimal> HOUSINCOME12 { get; set; }
        public Nullable<decimal> HOUSINCOME13 { get; set; }
        public Nullable<decimal> HOUSINCOME14 { get; set; }
        public Nullable<decimal> HOUSINCOME15 { get; set; }
        public Nullable<decimal> HOUSINCOME16 { get; set; }
        public Nullable<decimal> POV_LT_50 { get; set; }
        public Nullable<decimal> POV_50_74 { get; set; }
        public Nullable<decimal> POV_75_99 { get; set; }
        public Nullable<decimal> POV_100_124 { get; set; }
        public Nullable<decimal> POV_125_149 { get; set; }
        public Nullable<decimal> POV_150_174 { get; set; }
        public Nullable<decimal> POV_175_184 { get; set; }
        public Nullable<decimal> POV_185_199 { get; set; }
        public Nullable<decimal> POV_GT_200 { get; set; }
        public Nullable<decimal> ENGLISH_SPEAKER { get; set; }
        public Nullable<decimal> SPANISH_SPEAKER { get; set; }
        public Nullable<decimal> BORNINUS { get; set; }
        public Nullable<decimal> MOVEDINLAST12MON { get; set; }
        public Nullable<decimal> MARRIED { get; set; }
        public Nullable<decimal> DIVORCED { get; set; }
        public Nullable<decimal> DISABILITY { get; set; }
        public Nullable<decimal> UNEMPLOYMENT { get; set; }
        public Nullable<decimal> UNEMPLOYMENT_MALE { get; set; }
        public Nullable<decimal> INS_MEDICARE { get; set; }
        public Nullable<decimal> INS_MEDICAID { get; set; }
        public Nullable<decimal> HH_NOCAR { get; set; }
        public Nullable<decimal> HH_PUBLIC_ASSISTANCE { get; set; }
        public Nullable<decimal> HMOWNER_COSTS_MORT { get; set; }
        public Nullable<decimal> HMOWNER_COSTS_NO_MORT { get; set; }
        public Nullable<int> HOMES_MEDVALUE { get; set; }
        public Nullable<decimal> PCT_CROWDING { get; set; }
        public Nullable<decimal> FEMALE_HEAD_OF_HH { get; set; }
        public Nullable<decimal> MGR_FEMALE { get; set; }
        public Nullable<decimal> MGR_MALE { get; set; }
        public Nullable<decimal> RESIDENTS_65 { get; set; }
        public Nullable<decimal> SAME_RESIDENCE { get; set; }
        public Nullable<decimal> FAMPOVERTY { get; set; }
        public Nullable<decimal> HOUSPOVERTY { get; set; }
        public string ZIP { get; set; }
    }
}
