//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHORDS_VDWBuilder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEMOGRAPHICS
    {
        public string PERSON_ID { get; set; }
        public string MRN { get; set; }
        public System.DateTime BIRTH_DATE { get; set; }
        public string GENDER { get; set; }
        public string PRIMARY_LANGUAGE { get; set; }
        public string NEEDS_INTERPRETER { get; set; }
        public string RACE1 { get; set; }
        public string RACE2 { get; set; }
        public string RACE3 { get; set; }
        public string RACE4 { get; set; }
        public string RACE5 { get; set; }
        public string HISPANIC { get; set; }
        public string SEXUAL_ORIENTATION { get; set; }
        public string GENDER_IDENTITY { get; set; }
    }
}
