//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHORDS_VDWBuilder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIAGNOSES
    {
        public int DIAGNOSES_ID { get; set; }
        public string ENC_ID { get; set; }
        public string DX { get; set; }
        public System.DateTime ADATE { get; set; }
        public string DIAGPROVIDER { get; set; }
        public string PERSON_ID { get; set; }
        public string ENCTYPE { get; set; }
        public string PROVIDER { get; set; }
        public string ORIGDX { get; set; }
        public string DX_CODETYPE { get; set; }
        public string PRINCIPAL_DX { get; set; }
        public string PRIMARY_DX { get; set; }
    }
}
