//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHORDS_VDWBuilder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENCOUNTERS
    {
        public string ENC_ID { get; set; }
        public string PERSON_ID { get; set; }
        public System.DateTime ADATE { get; set; }
        public Nullable<System.DateTime> DDATE { get; set; }
        public string PROVIDER { get; set; }
        public decimal ENC_COUNT { get; set; }
        public string DRG_VERSION { get; set; }
        public string DRG_VALUE { get; set; }
        public string ENCTYPE { get; set; }
        public string ENCOUNTER_SUBTYPE { get; set; }
        public string FACILITY_CODE { get; set; }
        public string DISCHARGE_DISPOSITION { get; set; }
        public string DISCHARGE_STATUS { get; set; }
        public string ADMITTING_SOURCE { get; set; }
        public string DEPARTMENT { get; set; }
    }
}
