//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHORDS_VDWBuilder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENROLLMENT
    {
        public string PERSON_ID { get; set; }
        public System.DateTime ENR_START { get; set; }
        public System.DateTime ENR_END { get; set; }
        public string INS_MEDICAID { get; set; }
        public string INS_COMMERCIAL { get; set; }
        public string INS_PRIVATEPAY { get; set; }
        public string INS_STATESUBSIDIZED { get; set; }
        public string INS_SELFFUNDED { get; set; }
        public string INS_HIGHDEDUCTIBLE { get; set; }
        public string INS_MEDICARE { get; set; }
        public string INS_MEDICARE_A { get; set; }
        public string INS_MEDICARE_B { get; set; }
        public string INS_MEDICARE_C { get; set; }
        public string INS_MEDICARE_D { get; set; }
        public string INS_OTHER { get; set; }
        public string PLAN_HMO { get; set; }
        public string PLAN_POS { get; set; }
        public string PLAN_PPO { get; set; }
        public string PLAN_INDEMNITY { get; set; }
        public string DRUGCOV { get; set; }
        public string OUTSIDE_UTILIZATION { get; set; }
        public string ENROLLMENT_BASIS { get; set; }
        public string PCC { get; set; }
        public string PCP { get; set; }
    }
}
