//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHORDS_VDWBuilder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVERNDC
    {
        public string NDC { get; set; }
        public string GENERIC { get; set; }
        public string BRAND { get; set; }
        public string GPI { get; set; }
        public string AHFS1 { get; set; }
        public string AHFS2 { get; set; }
        public string AHFS3 { get; set; }
        public string AHFS4 { get; set; }
        public string AHFS5 { get; set; }
        public string AHFS6 { get; set; }
        public string AHFS7 { get; set; }
    }
}
