//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHORDS_VDWBuilder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LANGUAGES_ISO_LU
    {
        public string ISO_639_2_CODE { get; set; }
        public string ENGLISH_DESCRIPTION { get; set; }
    }
}
