//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHORDS_VDWBuilder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LANGUAGES
    {
        public string PERSON_ID { get; set; }
        public string LANG_ISO { get; set; }
        public string LANG_USAGE { get; set; }
        public string LANG_PRIMARY { get; set; }
    }
}
