//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHORDS_VDWBuilder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHARMACY
    {
        public int PHARMACY_ID { get; set; }
        public string PERSON_ID { get; set; }
        public System.DateTime RXDATE { get; set; }
        public string NDC { get; set; }
        public decimal RXSUP { get; set; }
        public decimal RXAMT { get; set; }
        public string RXMD { get; set; }
    }
}
