//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHORDS_VDWBuilder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCEDURES
    {
        public int PROCEDURES_ID { get; set; }
        public string ENC_ID { get; set; }
        public System.DateTime PROCDATE { get; set; }
        public string PERFORMINGPROVIDER { get; set; }
        public string ORIGPX { get; set; }
        public string PX { get; set; }
        public string PX_CODETYPE { get; set; }
        public string ROW_ID { get; set; }
        public string PERSON_ID { get; set; }
        public string PROVIDER { get; set; }
        public System.DateTime ADATE { get; set; }
        public string ENCTYPE { get; set; }
        public decimal PXCNT { get; set; }
        public string CPTMOD1 { get; set; }
        public string CPTMOD2 { get; set; }
        public string CPTMOD3 { get; set; }
    }
}
