//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHORDS_VDWBuilder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVIDER_SPECIALTY
    {
        public string PROVIDER { get; set; }
        public string SPECIALTY { get; set; }
        public string SPECIALTY2 { get; set; }
        public string SPECIALTY3 { get; set; }
        public string SPECIALTY4 { get; set; }
        public string PROVIDER_TYPE { get; set; }
        public Nullable<decimal> PROVIDER_BIRTH_YEAR { get; set; }
        public string PROVIDER_GENDER { get; set; }
        public string PROVIDER_RACE { get; set; }
        public string PROVIDER_HISPANIC { get; set; }
        public Nullable<decimal> YEAR_GRADUATED { get; set; }
    }
}
