//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHORDS_VDWBuilder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOCIAL_HISTORY
    {
        public int SOCIAL_HISTORY_ID { get; set; }
        public string PERSON_ID { get; set; }
        public System.DateTime CONTACT_DATE { get; set; }
        public string ENC_ID { get; set; }
        public string TOBACCO_PAK_PER_DY { get; set; }
        public string TOBACCO_USED_YEARS { get; set; }
        public string TOBACCO_COMMENT { get; set; }
        public string UNSPECIFIED_TOBACCO { get; set; }
        public Nullable<System.DateTime> SMOKING_QUIT_DATE { get; set; }
        public Nullable<System.DateTime> SMOKELESS_QUIT_DATE { get; set; }
        public string CIGARETTES_YN { get; set; }
        public string PIPES_YN { get; set; }
        public string CIGARS_YN { get; set; }
        public string SNUFF_YN { get; set; }
        public string CHEW_YN { get; set; }
        public string ALCOHOL_OZ_PER_WK { get; set; }
        public string ALCOHOL_COMMENT { get; set; }
        public string IV_DRUG_USER_YN { get; set; }
        public string ILLICIT_DRUG_FREQ { get; set; }
        public string ILLICIT_DRUG_COMMENT { get; set; }
        public string FEMALE_PARTNER_YN { get; set; }
        public string MALE_PARTNER_YN { get; set; }
        public string CONDOM_YN { get; set; }
        public string PILL_YN { get; set; }
        public string DIAPHRAGM_YN { get; set; }
        public string IUD_YN { get; set; }
        public string SURGICAL_YN { get; set; }
        public string SPERMICIDE_YN { get; set; }
        public string IMPLANT_YN { get; set; }
        public string RHYTHM_YN { get; set; }
        public string INJECTION_YN { get; set; }
        public string SPONGE_YN { get; set; }
        public string BC_INSERTS_YN { get; set; }
        public string ABSTINENCE_YN { get; set; }
        public string SEX_COMMENT { get; set; }
        public string YEARS_EDUCATION { get; set; }
        public string TOBACCO_USER { get; set; }
        public string ALCOHOL_USER { get; set; }
        public string ILL_DRUG_USER { get; set; }
        public string SEXUALLY_ACTV { get; set; }
        public string ONC_SMOKING_STATUS { get; set; }
    }
}
