//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHORDS_VDWBuilder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUMOR
    {
        public int TUMOR_ID { get; set; }
        public string PERSON_ID { get; set; }
        public string SEQUENCE { get; set; }
        public System.DateTime DXDATE { get; set; }
        public string ICDOSITE { get; set; }
        public string STAGEGEN { get; set; }
        public string SS1977 { get; set; }
        public string SS2000 { get; set; }
        public string STAGEAJ { get; set; }
        public string AJCC_ED { get; set; }
        public string AJCC_GRP { get; set; }
        public string AJCC_FULL_DER { get; set; }
        public string MORPH { get; set; }
        public string BEHAV { get; set; }
        public string GRADE { get; set; }
        public decimal DXYEAR { get; set; }
        public decimal DXAGE { get; set; }
        public System.DateTime BDATE { get; set; }
        public string GENDER { get; set; }
        public string RACE1 { get; set; }
        public string RACE2 { get; set; }
        public string RACE3 { get; set; }
        public string RACE4 { get; set; }
        public string RACE5 { get; set; }
        public string HISPANIC { get; set; }
        public string CLASS { get; set; }
        public string VITAL { get; set; }
        public string DCAUSE { get; set; }
        public Nullable<System.DateTime> DOD { get; set; }
        public Nullable<System.DateTime> DT_FU { get; set; }
        public string LATERALITY { get; set; }
        public string IDPLAN { get; set; }
        public string DCNFRM { get; set; }
        public string DSTZ { get; set; }
        public string DAJC1T_P { get; set; }
        public string DAJC1N_P { get; set; }
        public string DAJC1M_P { get; set; }
        public string DAJC1T_C { get; set; }
        public string DAJC1N_C { get; set; }
        public string DAJC1M_C { get; set; }
        public string DSRG_FAC { get; set; }
        public string DRAD_FAC { get; set; }
        public string DCHM_FAC { get; set; }
        public string DHRM_FAC { get; set; }
        public string DIMM_FAC { get; set; }
        public string DOTH_FAC { get; set; }
        public string DNDI { get; set; }
        public string DNDX { get; set; }
        public string DTMRK1 { get; set; }
        public string DTMRK2 { get; set; }
        public string DTMRK3 { get; set; }
        public string CLN_STG { get; set; }
        public string EOD { get; set; }
        public Nullable<System.DateTime> DT_SURG { get; set; }
        public Nullable<System.DateTime> DT_CHEMO { get; set; }
        public Nullable<System.DateTime> DT_HORM { get; set; }
        public Nullable<System.DateTime> DT_RAD { get; set; }
        public Nullable<System.DateTime> DT_BRM { get; set; }
        public Nullable<System.DateTime> DT_OTH { get; set; }
        public string R_N_SURG { get; set; }
        public string R_N_CHEMO { get; set; }
        public string R_N_HORM { get; set; }
        public string R_N_RAD { get; set; }
        public string R_N_BRM { get; set; }
        public string R_N_OTH { get; set; }
        public string DSRG_SUM { get; set; }
        public string DRAD_SUM { get; set; }
        public string DCHM_SUM { get; set; }
        public string DHRM_SUM { get; set; }
        public string DIMM_SUM { get; set; }
        public string DOTH_SUM { get; set; }
        public string CS_SZ { get; set; }
        public string CS_EXT { get; set; }
        public string CS_NODES { get; set; }
        public string CS_NODES_EVAL { get; set; }
        public string CS_METS { get; set; }
        public string CS_METS_EVAL { get; set; }
        public string SSF1 { get; set; }
        public string SSF2 { get; set; }
        public string SSF3 { get; set; }
        public string SSF4 { get; set; }
        public string SSF5 { get; set; }
        public string SSF6 { get; set; }
        public string SSF7 { get; set; }
        public string SSF8 { get; set; }
        public string SSF9 { get; set; }
        public string SSF10 { get; set; }
        public string SSF11 { get; set; }
        public string SSF12 { get; set; }
        public string SSF13 { get; set; }
        public string SSF14 { get; set; }
        public string SSF15 { get; set; }
        public string SSF16 { get; set; }
        public string SSF17 { get; set; }
        public string SSF18 { get; set; }
        public string SSF19 { get; set; }
        public string SSF20 { get; set; }
        public string SSF21 { get; set; }
        public string SSF22 { get; set; }
        public string SSF23 { get; set; }
        public string SSF24 { get; set; }
        public string SSF25 { get; set; }
        public string PAL_FAC { get; set; }
        public string PAL_SUM { get; set; }
        public string DER_T6 { get; set; }
        public string DER_T6_D { get; set; }
        public string DER_N6 { get; set; }
        public string DER_N6_D { get; set; }
        public string DER_M6 { get; set; }
        public string DER_M6_D { get; set; }
        public string DER_T7 { get; set; }
        public string DER_T7_D { get; set; }
        public string DER_N7 { get; set; }
        public string DER_N7_D { get; set; }
        public string DER_M7 { get; set; }
        public string DER_M7_D { get; set; }
        public string DER_SS2000F { get; set; }
        public Nullable<System.DateTime> RECUR_DT { get; set; }
        public string RECUR_TYPE { get; set; }
        public string RECUR_FL { get; set; }
        public string DATA_SOURCE { get; set; }
    }
}
