//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHORDS_VDWBuilder.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VDW_3_1_Entities : DbContext
    {
        public VDW_3_1_Entities()
            : base("name=VDW_3_1_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ABN_IND_LU> ABN_IND_LU { get; set; }
        public virtual DbSet<ADMITTING_SOURCE_LU> ADMITTING_SOURCE_LU { get; set; }
        public virtual DbSet<BP_TYPE_LU> BP_TYPE_LU { get; set; }
        public virtual DbSet<CAUSE_OF_DEATH> CAUSE_OF_DEATH { get; set; }
        public virtual DbSet<CAUSETYPE_LU> CAUSETYPE_LU { get; set; }
        public virtual DbSet<CENSUS_DEMOG> CENSUS_DEMOG { get; set; }
        public virtual DbSet<CENSUS_LOCATION> CENSUS_LOCATION { get; set; }
        public virtual DbSet<CODETYPE_LU> CODETYPE_LU { get; set; }
        public virtual DbSet<COLORADO_COUNTIES> COLORADO_COUNTIES { get; set; }
        public virtual DbSet<CONFIDENCE_LU> CONFIDENCE_LU { get; set; }
        public virtual DbSet<DEATH> DEATH { get; set; }
        public virtual DbSet<DEMOGRAPHICS> DEMOGRAPHICS { get; set; }
        public virtual DbSet<DEPARTMENT_LU> DEPARTMENT_LU { get; set; }
        public virtual DbSet<DIAGNOSES> DIAGNOSES { get; set; }
        public virtual DbSet<DISCHARGE_DISPOSITION_LU> DISCHARGE_DISPOSITION_LU { get; set; }
        public virtual DbSet<DISCHARGE_STATUS_LU> DISCHARGE_STATUS_LU { get; set; }
        public virtual DbSet<DTIMPUTE_LU> DTIMPUTE_LU { get; set; }
        public virtual DbSet<DX_CODETYPE_LU> DX_CODETYPE_LU { get; set; }
        public virtual DbSet<ENCOUNTER_SUBTYPE_LU> ENCOUNTER_SUBTYPE_LU { get; set; }
        public virtual DbSet<ENCOUNTERS> ENCOUNTERS { get; set; }
        public virtual DbSet<ENCTYPE_LU> ENCTYPE_LU { get; set; }
        public virtual DbSet<ENROLLMENT> ENROLLMENT { get; set; }
        public virtual DbSet<ENROLLMENT_BASIS_LU> ENROLLMENT_BASIS_LU { get; set; }
        public virtual DbSet<EVERNDC> EVERNDC { get; set; }
        public virtual DbSet<GENDER_IDENTITY_LU> GENDER_IDENTITY_LU { get; set; }
        public virtual DbSet<GENDER_LU> GENDER_LU { get; set; }
        public virtual DbSet<LAB_RESULTS> LAB_RESULTS { get; set; }
        public virtual DbSet<LANG_USAGE_LU> LANG_USAGE_LU { get; set; }
        public virtual DbSet<LANGUAGES> LANGUAGES { get; set; }
        public virtual DbSet<LANGUAGES_ISO_LU> LANGUAGES_ISO_LU { get; set; }
        public virtual DbSet<MODIFIER_LU> MODIFIER_LU { get; set; }
        public virtual DbSet<ONC_SMOKING_STATUS_LU> ONC_SMOKING_STATUS_LU { get; set; }
        public virtual DbSet<PHARMACY> PHARMACY { get; set; }
        public virtual DbSet<POSITION_LU> POSITION_LU { get; set; }
        public virtual DbSet<PRESCRIBING> PRESCRIBING { get; set; }
        public virtual DbSet<PRIMARY_DX_LU> PRIMARY_DX_LU { get; set; }
        public virtual DbSet<PRINCIPAL_DX_LU> PRINCIPAL_DX_LU { get; set; }
        public virtual DbSet<PROCEDURES> PROCEDURES { get; set; }
        public virtual DbSet<PROVIDER_SPECIALTY> PROVIDER_SPECIALTY { get; set; }
        public virtual DbSet<PROVIDER_TYPE_LU> PROVIDER_TYPE_LU { get; set; }
        public virtual DbSet<PT_LOC_LU> PT_LOC_LU { get; set; }
        public virtual DbSet<PX_CODETYPE_LU> PX_CODETYPE_LU { get; set; }
        public virtual DbSet<RACE_LU> RACE_LU { get; set; }
        public virtual DbSet<RESULT_LOC_LU> RESULT_LOC_LU { get; set; }
        public virtual DbSet<RX_BASIS_LU> RX_BASIS_LU { get; set; }
        public virtual DbSet<RX_FREQUENCY_LU> RX_FREQUENCY_LU { get; set; }
        public virtual DbSet<RX_QUANTITY_UNIT_LU> RX_QUANTITY_UNIT_LU { get; set; }
        public virtual DbSet<SEXUAL_ORIENTATION_LU> SEXUAL_ORIENTATION_LU { get; set; }
        public virtual DbSet<SEXUALLY_ACTV_LU> SEXUALLY_ACTV_LU { get; set; }
        public virtual DbSet<SOCIAL_HISTORY> SOCIAL_HISTORY { get; set; }
        public virtual DbSet<SPECIMEN_SOURCE_LU> SPECIMEN_SOURCE_LU { get; set; }
        public virtual DbSet<STAT_LU> STAT_LU { get; set; }
        public virtual DbSet<TOBACCO_USER_LU> TOBACCO_USER_LU { get; set; }
        public virtual DbSet<TUMOR> TUMOR { get; set; }
        public virtual DbSet<VITAL_SIGNS> VITAL_SIGNS { get; set; }
        public virtual DbSet<YNQXU_LU> YNQXU_LU { get; set; }
        public virtual DbSet<YNU_LU> YNU_LU { get; set; }
        public virtual DbSet<YNXU_LU> YNXU_LU { get; set; }
    }
}
