//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHORDS_VDWBuilder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VITAL_SIGNS
    {
        public int VITAL_SIGNS_ID { get; set; }
        public string PERSON_ID { get; set; }
        public System.DateTime MEASURE_DATE { get; set; }
        public System.TimeSpan MEASURE_TIME { get; set; }
        public string ENC_ID { get; set; }
        public string ENCTYPE { get; set; }
        public string HT_RAW { get; set; }
        public string WT_RAW { get; set; }
        public Nullable<decimal> HT { get; set; }
        public Nullable<decimal> WT { get; set; }
        public string BMI_RAW { get; set; }
        public Nullable<decimal> DIASTOLIC { get; set; }
        public Nullable<decimal> SYSTOLIC { get; set; }
        public string DIASTOLIC_RAW { get; set; }
        public string SYSTOLIC_RAW { get; set; }
        public string BP_TYPE { get; set; }
        public string POSITION { get; set; }
        public string HEAD_CIR_RAW { get; set; }
        public string RESPIR_RAW { get; set; }
        public string TEMP_RAW { get; set; }
        public string PULSE_RAW { get; set; }
    }
}
